# Am example config file for `box_tri_generator.py`

head: 0
tail: 20

data:
  gd_folder: 'gd'
  gn_file: 'gn'
  model: 'triangle'
  kind: 'equ'
  num_cir: 2
  rlim: [0.2, 0.4]
  major_lim: [2.0, 6.0]
  ecc_lim: [0.5, 1.0]
  sigma: [10., 1.]
  ext: 63
  freq: [1, 2, 3, 4, 5, 6, 8, 16]

label:
  label_folder: 'inclusion'
  dtype: 'float32'
  transition: 'bool'

fem:
  p: 1
  q: 3

backend: 'numpy'
seed: 26710
seed_offsets: [621, 928, 122, 222]
num_process: 4
output_folder: './tmp'
